server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.1.106
  rabbitmq:
    host: 192.168.1.106
    username: gmall
    password: gmall
    virtual-host: /gmall
gmall:
  jwt:
    pubKeyPath: D:\\project\\ras\\rsa.pub # ¹«Ô¿µØÖ·
    cookieName: GMALL_TOKEN
    userKey: user-key