spring:
  application:
    name: auth-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
gmall:
  jwt:
    pubKeyPath: D:\\project\\ras\\rsa.pub # 公钥地址
    priKeyPath: D:\\project\\ras\\rsa.pri # 私钥地址
    secret: sf3423jsdf#3$@FDS32
    expire: 100 # 过期时间,单位分钟
    cookieName: GMALL_TOKEN